### ISSUE TITLE
setup: "copy to" path for windows version of netbeans

### ISSUE THREAD

**Issue by istinnstudio** [mbien/jackpot-inspections#1]
what is the equivalent of "copy to ~/.netbeans/[version]/conf/rules" path, for windows version of netbeans? thanks...

**Comment by mbien** [comment]
NetBeans should tell you in the about window:
https://github.com/apache/netbeans#log-config-and-cache-locations
(also in the log but probably less convenient)

**Comment by istinnstudio** [comment]
That is the answer, it works, thanks!
the path is:
X:\Users\USER\AppData\Roaming\NetBeans\VERSION\config\rules
