### ISSUE TITLE
Unable to install on macOS

### ISSUE THREAD

**Issue by gwinstanley** [mbien/jackpot-inspections#2]
This collection of hints is very useful, but I'm having trouble using them across multiple projects on macOS. They successfully get recognised by NetBeans 16 for a single project when the hints are in the project's `src/main/resources/META-INF/upgrade` directory, but I can't make NB notice them when either in `$HOME/Library/Application Support/NetBeans/16/conf/rules` (what I'd expect for macOS) or `$HOME/.netbeans/16/conf/rules` (what I'd expect for Linux, and also the README advice).

Given how useful they seem to be as a hints collection (thank you!), would you be able to suggest how I might get them working on macOS/NetBeans?

**Comment by mbien** [comment]
oh interesting. I would have to ask a mac user where to put those rules on mac os. I don't know it either. Could be also a bug in NetBeans potentially.

**Comment by mbien** [comment]
what if you open `refactor -> inspect and transform` then select `single inspection` and press `browse`.

now you press `new` and then `edit script` this should open an empty hint file in the editor. The path to the file should be the `rules` folder - wherever that is on mac os.

**Comment by gwinstanley** [comment]
Excellent, that `edit script` trick did it; should have thought of doing that myself. The relevant path for macOS is `$HOME/Library/Application Support/NetBeans/16/config/rules` (note `config` instead of `conf`). Now I've placed them in there things work as expected across projects. Many thanks.
